# GLOBAL SITE SETTINGS

cname: danandmitch.com

# META
title: Dan & Mitch
title_homepage: Dan & Mitch ON - Games, Movies, Nerd Culture, YouTube
company: Dan & Mitch Network
description: Dan & Mitch is a YouTube channel that covers Gaming, Movies and Nerd Culture.

# SITE DEFAULTS
site_tagline: "NEW SHOWS <span class='font-normal'>every</span> DECADE"

# DEVELOPER
allow_robots: true
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/danandmitch.com
github_repo_name: danandmitch.com
jekyll_version: 3.0.3

# OFFICES
offices:
  - title: Sydney
    address: N/A
    email: danandmitchon@gmail.com

# SOCIAL MEDIA
facebook: https://www.facebook.com/DanAndMitch/
youtube: https://www.youtube.com/channel/UC4S74VhUhaL1HGv3kxYyH6Q
youtube_subscribe: https://www.youtube.com/channel/UC4S74VhUhaL1HGv3kxYyH6Q
youtube_subscribe_tmh: https://www.youtube.com/channel/UCyhc20wvZZ_ODC-EzSErDjg
google_plus:
instagram: https://www.instagram.com/danandmitch/
twitter: http://twitter.com/danandmitch/

# GOOGLE
google_analytics: UA-71596790-1

# AUTHOR
author:
  title: Mitch
  url: http://liquidvisual.com
  logo: /assets/img/ui/liquidvisual-logo.svg
  description: Site by liquidvisual

# PLAYLISTS
playlists:
  ON_TOPIC: https://www.youtube.com/watch?v=Ng6GxPEs5Uc&list=PLnu_-2Pyhu4EoL_AT8ogXGmdawDi9tAV8
  ON_TECH: https://www.youtube.com/watch?v=22XqmGdfyRs&list=PLnu_-2Pyhu4EssVi3zpUGsTSs5kowIcLM
  ON_GAMES: https://www.youtube.com/watch?v=kpCoU9_2pJI&list=PLnu_-2Pyhu4Fb7IvvY-Ii8sr-dQBx7aRj
  NETFLIX_BINGE: https://www.youtube.com/watch?v=tQVYryELnp8&list=PLnu_-2Pyhu4HG9kzfObBnajnpW4ynioEF
  MOVIE_REVIEWS: https://www.youtube.com/watch?v=I5gkR6BdDhA&list=PLnu_-2Pyhu4HO_obsL9AuyOxTd2aeh65g
  SHOW_AND_TELL: https://www.youtube.com/watch?v=0MuEo8OMauo&list=PLnu_-2Pyhu4FWaJmawnC31N13LbI-Ziwr
  ANOTHER_NERDY_PODCAST: https://www.youtube.com/watch?v=XebwH533TuI&list=PLnu_-2Pyhu4GRBMQqo5sdDUWumAQn0x64
  REACTION: https://www.youtube.com/watch?v=5Iok9GBWkpo&list=PLnu_-2Pyhu4Hcev1V3LOObngv1sBTbfuV
  TOP_TEN: https://www.youtube.com/watch?v=FgsT1xY4q40&list=PLnu_-2Pyhu4GpK6lGu8j6J5zj7gAMRohM