# GLOBAL SITE SETTINGS

cname: danandmitch.com

# META
title: Dan & Mitch
title_homepage: Dan & Mitch ON - Games, Movies, Nerd Culture, YouTube
company: Dan & Mitch Network
description: Dan & Mitch is a YouTube channel that covers Gaming, Movies and Nerd Culture.

# SITE DEFAULTS
site_tagline: "NEW SHOWS <span class='font-normal'>every</span> DECADE"

# DEVELOPER
allow_robots: true
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/danandmitch.com
github_repo_name: danandmitch.com
jekyll_version: 3.0.3

# OFFICES
offices:
  - title: Sydney
    address: N/A
    email: danandmitchon@gmail.com

# SOCIAL MEDIA
facebook: https://www.facebook.com/DanAndMitch/
youtube: https://www.youtube.com/channel/UC4S74VhUhaL1HGv3kxYyH6Q
youtube_subscribe: https://www.youtube.com/channel/UC4S74VhUhaL1HGv3kxYyH6Q
youtube_subscribe_tmh: https://www.youtube.com/channel/UCyhc20wvZZ_ODC-EzSErDjg
google_plus:
instagram: https://www.instagram.com/danandmitch/
twitter: http://twitter.com/danandmitch/

# GOOGLE
google_analytics: UA-71596790-1

# AUTHOR
author:
  title: Mitch
  url: http://liquidvisual.com
  logo: /assets/img/ui/liquidvisual-logo.svg
  description: Site by liquidvisual